### PR TITLE
fix: preadv2 only available on GNU libc

### LINKED ISSUE #79: 0.1.29 doesn't build against musl libc.
For example, building in an alpine container:

```
6.767 error[E0425]: cannot find function `preadv2` in crate `libc`
6.767     --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jobserver-0.1.29/src/unix.rs:598:15
6.767      |
6.767 598  |           libc::preadv2(
6.767      |                 ^^^^^^^ help: a function with a similar name exists: `preadv`
6.767      |
6.767     ::: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/linux_like/linux/mod.rs:4868:13
6.767      |
6.767 4868 | /             pub fn preadv(
6.767 4869 | |                 fd: ::c_int,
6.767 4870 | |                 iov: *const ::iovec,
6.767 4871 | |                 iovcnt: ::c_int,
6.767 4872 | |                 offset: ::off_t,
6.767 4873 | |             ) -> ::ssize_t;
6.767      | |__________________________- similarly named function `preadv` defined here
6.767
6.768 error[E0425]: cannot find value `RWF_NOWAIT` in crate `libc`
6.768     --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jobserver-0.1.29/src/unix.rs:606:19
6.768      |
6.768 606  |             libc::RWF_NOWAIT,
6.768      |                   ^^^^^^^^^^ help: a constant with a similar name exists: `IPC_NOWAIT`
6.768      |
6.768     ::: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/linux_like/linux/mod.rs:2102:1
6.768      |
6.768 2102 | pub const IPC_NOWAIT: ::c_int = 0o4000;
6.768      | ----------------------------- similarly named constant `IPC_NOWAIT` defined here
6.768
6.821 For more information about this error, try `rustc --explain E0425`.
```

https://docs.rs/libc/latest/x86_64-unknown-linux-musl/libc/index.html?search=preadv2

### PR DESCRIPTION
**Pull request by weihanglo**
Technicially it is also available on musl libc 1.2.5,
yet the libc@0.2.153 (lastet) doesn't export the symbol,
and that version of musl libc is too new (released in 2024-03)

Fixes #79. Tested against Rust docker image [alpine3.18](https://github.com/rust-lang/docker-rust/blob/73b57d936481598421d27c4d722a24774a2267ea/1.77.2/alpine3.18/Dockerfile)

### CODE REVIEW

**Comment by weihanglo** [comment]
@petrochenkov

Could you help do a `0.1.30` release, and after the release yank 0.1.29 then?

**Comment by petrochenkov** [comment]
@weihanglo @NobodyXu 
Could you check https://github.com/rust-lang/jobserver-rs/pull/82?
It seems fine, but I'm not well trained in noticing issues in CI scripts.
I'll make a release once that PR lands.

**Comment by weihanglo** [comment]
It looks great. It also failed without this PR and now passed, so r+.

**Comment by weihanglo** [comment]
#82 is just merged.

**Comment by petrochenkov** [comment]
Published 0.1.30 and yanked 0.1.29.

**Pull request merged**
