### PR TITLE
fix: remove preadv2 optimization

### PR DESCRIPTION
**Pull request by weihanglo**
This optimization has introduced many compatibility issues, so remove it for now until we find it worthy the investment.

See also

* <https://github.com/rust-lang/cc-rs/issues/1039>
* <https://github.com/rust-lang/jobserver-rs/issues/87>

### CODE REVIEW

**Comment by the8472** [comment]
You can use `libc::syscall(SYS_preadv2, ...)` to invoke the function without direct glibc support. If the kernel doesn't support it you'll get ENOSYS as usual.

**Comment by weihanglo** [comment]
Thanks! That sounds also correct, though I personally don't have time investing in it (also have less experience of that). Need somebody else to work on that route.

**Comment by ofek** [comment]
If it's not a one or two line change then I agree that we should revert for now to fix builds. I would be interested in the syscall change however because that seems simple but I'm not familiar with the code base.

**Comment by ofek** [comment]
When might this be released?

**Comment by NobodyXu** [comment]
I've asked @petrochenkov to do so on zulip, only they have the right to publish a new release

**Pull request merged**
