### PR TITLE
Redox support

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I'm a little uncomfortable with the amount of ad-hoc duplication here and `#[cfg]` magic, perhaps redox could just have an entirely separate implementation module?

**Comment by jackpot51** [comment]
Sure thing, that would be possible

**Comment by petrochenkov** [comment]
@jackpot51 
Is there still interest in supporting this crate on Redox?
The current implementation is 5 years old, it probably needs an update now.
If there's no interest, then we'll close this PR to cleanup the queue.

**Comment by jackpot51** [comment]
I am fairly certain this is longer needed.

**Pull request closed without merging**
