### PR TITLE
Change: make license spdx compliant

### PR DESCRIPTION
**Pull request by jjnicola**
Make license spdx compliant.

### CODE REVIEW

**Review by weihanglo — APPROVED** [review]

**Comment by ArnoStiefvater** [comment]
Hello @weihanglo

its not super urgent so no stress, but do you have an estimate when this will be merged and released?

**Comment by petrochenkov** [comment]
Please, ping me if you need to merge or release something, I have the owner rights now.

**Comment by ArnoStiefvater** [comment]
Hello @petrochenkov,

could you do a new release?

**Comment by weihanglo** [comment]
@ArnoStiefvater `jobserver@0.1.28` should already have this patch.

**Comment by jjnicola** [comment]
Thank you very much @weihanglo

**Pull request merged**
